server:
    port: 8089
    servlet:
        context-path: /uaa
        
spring:
    thymeleaf:
        cache: false  
       
security:
    basic:    
        enabled: false
        
keystore:
    jks: jwtkey.jks
    keyname: jwtkey
    password: aaaaaa       
