server:
    port: 8089
    servlet:
        context-path: /uaa
       
spring:
    application:
        email: ${{ EMAIL_SERVER_USERNAME }}
    thymeleaf:
        cache: false  
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_SERVER_USERNAME}
        password: ${EMAIL_SERVER_PASSWORD}
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        
keystore:
    jks: jwtkey.jks
    keyname: jwtkey
    password: aaaaaa   
    
google:
    recaptcha:
        key:
            site: ${GOOLE_RECAPTCHA_KEY_SITE}
            secret: ${GOOLE_RECAPTCHA_KEY_SECRET}
