server:
    port: 8089
    servlet:
        context-path: /uaa
        
spring:
    thymeleaf:
        cache: false  
    mail:
        host: smtp.gmail.com
        port: 587
        username: freeland.rokas@gmail.com
        password: xxxxxxx
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        
security:
    basic:    
        enabled: false
        
keystore:
    jks: jwtkey.jks
    keyname: jwtkey
    password: aaaaaa        
        
google:
    recaptcha:
        key:
            site: 6LdipIkUAAAAAPJomQ796W15djLMc8zR_WnVEOlp
            secret: 6LdipIkUAAAAAFORvNfm3CwUT8SYDnC_-dy-WDqt
